spring:
  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB

  jackson:
    time-zone: Asia/Seoul

  web:
    error:
      include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

aws:
  s3:
    bucket: ${S3_BUCKET_NAME:local-test-bucket}
    region: ${AWS_REGION:ap-northeast-2}

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
