spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  sql:
    init:
      mode: never

# 운영 로그에는 SQL과 개인정보를 출력하지 않는다.
decorator:
  datasource:
    p6spy:
      enable-logging: false
